// Validates data/reserves.json and generates:
//   supabase/seed-reserves.sql  — run in Supabase SQL Editor (safe to re-run)
//   data/reserves-review.csv    — open in Excel to review the list
//
//   node scripts/reserves/build.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = (p) => fileURLToPath(new URL(`../../${p}`, import.meta.url));
const data = JSON.parse(readFileSync(root('data/reserves.json'), 'utf8'));

const STATUSES = ['open', 'limited', 'closed', 'unknown'];

const PROVINCES = [
  'Eastern Cape', 'Free State', 'Gauteng', 'KwaZulu-Natal', 'Limpopo',
  'Mpumalanga', 'North West', 'Northern Cape', 'Western Cape',
];

// ---- validate -------------------------------------------------------------
const errors = [];
const seen = new Set();
for (const [i, r] of data.reserves.entries()) {
  const where = `#${i + 1} ${r.name ?? '(no name)'}`;
  if (!r.name?.trim()) errors.push(`${where}: missing name`);
  if (!r.org?.trim()) errors.push(`${where}: missing org`);
  if (!PROVINCES.includes(r.province)) errors.push(`${where}: unknown province "${r.province}"`);
  if (seen.has(r.name)) errors.push(`${where}: duplicate name`);
  seen.add(r.name);
  const hasLat = typeof r.lat === 'number';
  const hasLng = typeof r.lng === 'number';
  if (hasLat !== hasLng) errors.push(`${where}: lat and lng must both be set or both be empty`);
  if (r.status !== undefined && !STATUSES.includes(r.status)) errors.push(`${where}: unknown status "${r.status}"`);
  if (r.status && !r.checked) errors.push(`${where}: has a status but no "checked" date`);
}
for (const x of data.excluded ?? []) {
  if (seen.has(x.name)) errors.push(`"${x.name}" is both in reserves and excluded`);
  if (!x.reason) errors.push(`excluded "${x.name}": missing reason`);
}
if (errors.length) {
  console.error('reserves.json has problems:\n  ' + errors.join('\n  '));
  process.exit(1);
}

// ---- SQL ------------------------------------------------------------------
const sql = (v) => (v === undefined || v === null ? 'null' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`);

const values = data.reserves
  .map((r) => `  (${sql(r.name)}, ${sql(r.org)}, ${sql(r.province)}, ${sql(r.lat)}, ${sql(r.lng)})`)
  .join(',\n');

const seed = `-- GENERATED by scripts/reserves/build.mjs from data/reserves.json — don't edit by hand.
-- Run in Supabase → SQL Editor. Safe to re-run: adds new reserves, updates
-- existing ones (matched by name), and removes reserves that are no longer in
-- the list — but only if nobody has stamped them.

create unique index if not exists reserves_name_key on reserves (name);

insert into reserves (name, org, province, lat, lng) values
${values}
on conflict (name) do update set
  org = excluded.org,
  province = excluded.province,
  lat = excluded.lat,
  lng = excluded.lng;

-- Remove reserves that are no longer in the list and have no stamps.
delete from reserves r
where r.name not in (
${data.reserves.map((r) => '  ' + sql(r.name)).join(',\n')}
)
and not exists (select 1 from stamps s where s.reserve_id = r.id);

-- Anything left that ISN'T in the list still has stamps on it — shown here so
-- it can be handled by hand (e.g. move those stamps to the right reserve).
select r.name as "not in list but has stamps", count(s.id) as stamps
from reserves r join stamps s on s.reserve_id = r.id
where r.name not in (
${data.reserves.map((r) => '  ' + sql(r.name)).join(',\n')}
)
group by r.name;
`;
writeFileSync(root('supabase/seed-reserves.sql'), seed);

// ---- CSV for review -------------------------------------------------------
const csv = (v) => {
  const s = v === undefined || v === null ? '' : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
const header = [
  'Province', 'Organisation', 'Reserve', 'Status', 'Status note', 'Last checked',
  'Decision needed', 'Notes', 'Has map location', 'Sources',
];
const byPlace = (a, b) =>
  a.province.localeCompare(b.province) || a.org.localeCompare(b.org) || a.name.localeCompare(b.name);
const lines = [header.join(',')].concat(
  [...data.reserves].sort(byPlace).map((r) =>
    [
      r.province, r.org, r.name, r.status ?? 'not checked yet', r.status_note ?? '', r.checked ?? '',
      r.check ?? '', r.note ?? '', typeof r.lat === 'number' ? 'yes' : 'NO', (r.sources ?? []).join(' '),
    ]
      .map(csv)
      .join(','),
  ),
  [...(data.excluded ?? [])].sort(byPlace).map((x) =>
    [x.province, x.org, x.name, 'EXCLUDED', x.reason, x.checked ?? '', '', '', '', (x.sources ?? []).join(' ')]
      .map(csv)
      .join(','),
  ),
);
// BOM so Excel opens it as UTF-8 (names like ǀAi-ǀAis, en dashes)
writeFileSync(root('data/reserves-review.csv'), '﻿' + lines.join('\r\n') + '\r\n');

// ---- summary --------------------------------------------------------------
const count = (pred) => data.reserves.filter(pred).length;
console.log(`${data.reserves.length} reserves`);
for (const p of PROVINCES) console.log(`  ${p.padEnd(14)} ${count((r) => r.province === p)}`);
for (const s of STATUSES) console.log(`Status ${s.padEnd(8)} ${count((r) => r.status === s)}`);
console.log(`Status not checked yet: ${count((r) => !r.status)}`);
console.log(`Excluded: ${(data.excluded ?? []).length}`);
console.log(`Decision needed: ${count((r) => r.check)}`);
console.log(`Missing map location: ${count((r) => typeof r.lat !== 'number')}`);
console.log('Wrote supabase/seed-reserves.sql and data/reserves-review.csv');
